version: '3.4'

services:
  kata.api:
    image: ${DOCKER_REGISTRY-}kata.api
    container_name: kata.api
    build:
      context: .
      dockerfile: src/api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:EmployeeDB:HostName=kata.db"
      - "ConnectionStrings:EmployeeDB:Catalogue=kata"
      - "ConnectionStrings:EmployeeDB:User=sa"
      - "ConnectionStrings:EmployeeDB:Password=.123Pass456."
    ports:
      - "9010:80"
    depends_on:
      - kata.db

  kata.db:
    image: mcr.microsoft.com/mssql/server
    container_name: kata.db
    restart: always
    volumes:
      - /c/data/docker/database:/var/opt/mssql/data
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: ".123Pass456."
      ACCEPT_EULA: "Y"